### ISSUE TITLE
Data attributes

### ISSUE THREAD

**Issue by MichaelRise** [sarcadass/granim.js#30] opened 2017-07-21 17:14 UTC
Hey,

I have one problem.
I can't add gradients via data attribute.

V1 - this works ok:
```
var my_gradient = [['#000000', '#111111'],['#444444', '#777777'],['#aaaaaa', '#ffffff']];
var granimInstance = new Granim({
	states : {
		"default-state": {
			gradients: my_gradient
		}
	}
});
```

V2 - Don't work
```
var my_gradient = el.getAttribute('data-gradients') || [['#000000', '#111111'],['#444444', '#777777'],['#aaaaaa', '#ffffff']];
var granimInstance = new Granim({
	states : {
		"default-state": {
			gradients: my_gradient
		}
	}
});
```
```
<div data-gradients="[['#000000', '#111111'],['#444444', '#777777'],['#aaaaaa', '#ffffff']]">
	<canvas></canvas>
</div>
```
Please help.

**Comment by sarcadass** [comment] 2017-07-25 12:19
Hello @MichaelRise ,
Can you please reproduce the issue on [jsfiddle](https://jsfiddle.net/) or [codepen](https://codepen.io/), it will be easier to debug.
Thank you

**Comment by SebaGnich** [comment] 2017-09-11 09:28
I guess it's because "my_gradient" is a string in the second case. You'll need to decode that with
`my_gradient = JSON.parse(my_gradient);`

**Comment by pranaygp** [comment] 2017-09-11 16:26
@SebaGnich is right. It's likely because of that.

Closing this issue but feel free to reopen if the issue persists :)

**Closed by pranaygp** 2017-09-11 16:26 UTC

**Comment by MichaelRise** [comment] 2017-09-14 15:26
@SebaGnich Thanks ;)
Single quotes are not correctly formatted in json so I must use `.replace(/'/g, '"')`
Final code:
`var my_gradient = JSON.parse( gElement.getAttribute('data-gradients').replace(/'/g, '"') )`

**Comment by SebaGnich** [comment] 2017-09-14 15:58
Would be better to have it (the doublequotes ") encoded already in the Attributes. 
Because something like
'It's me, Mario!' would end in
"It"s me, Mario!".
You get it :)

**Comment by MichaelRise** [comment] 2017-09-14 16:58
Yes, I know.
I must add gradients via the data attributes and I can't use doublequotes - this solution is easier to edit for users and I can use it multiple times.
